--- 
project_name: docker-machine-driver-vmware
before:
  hooks:
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch: 
      - amd64
archives:
  - id: github
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format: tar.gz
    files:
    - LICENSE*
    - README*
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^typo'
      - 'version bump'
# brews:
#   - folder: Formula
#     tap:
#       owner: mikeroySoft
#       name: homebrew-tap
#     commit_author:
#       name: Michael Roy
#       email: mike@mikeroysoft.com
#     homepage: "https://github.com/machine-drivers/docker-machine-driver-vmware/blob/master/README.md"
#     description: "Cross-platform docker-machine driver for VMware Fusion and Workstation"
#     test: |
#       system "#{bin}/docker-machine-driver-vmware -v"
#     install: |
#       bin.install "docker-machine-driver-vmware"